##
## Copyright (c) 2021 Patrice Congo <@congop>.
##
## This file is part of io_patricecongo.spire
## (see https://github.com/congop/io_patricecongo.spire).
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program. If not, see <http://www.gnu.org/licenses/>.##

# just setting python interpreter apropriatly
# by using PROJECT_ANSIBLE_PYTHON_INTERPRETER we expect to pick the interpreter used to start molecule
#   - which should be be the python auf the virtual environmemnt with all the necessary python modules

all:
  hosts:
    localhost:
      ansible_python_interpreter: "{{ lookup('env','PROJECT_ANSIBLE_PYTHON_INTERPRETER') }}"
      ansible_connection: local
    # spire_server:
    #   ansible_python_interpreter: "/usr/bin/python3"
    # spire_agent:
    #   ansible_python_interpreter: "/usr/bin/python3"
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    ANSIBLE_KEEP_REMOTE_FILES: 1
